apiVersion: v1
kind: Pod
metadata:
  name: ephermeral-vol-example
spec:
  containers:
  # Main Application Container
  - name: cont-main
    image: alpine
    command: ["/bin/sh", "-c"]
    args: 
    - >
      while true; do
        echo "$(date) - Application transaction successful." >> /var/log/app/output.log;
        sleep 5;
      done
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/app

  # Sidecar Container (Log Shipper/Processor)
  - name: cont-sidecar
    image: alpine
    command: ["/bin/sh", "-c"]
    args: ["tail -f /var/log/app/output.log"]
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/app

  # Shared Ephemeral Volume
  volumes:
  - name: log-volume
    emptyDir: {}

