apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  maxReplicas: 100
  metrics:
  - resource:
      name: cpu
      target:
        averageValue: 50m
        type: AverageValue
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deploy
  behaviour:
    scaleDown:
      stabilizationWindowSeconds: 30
status:
  currentMetrics: null
  desiredReplicas: 0
