apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deploy
  name: my-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: my-deploy
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        command:
          - /bin/bash
          - -c
          - |
            while true;
            do :;
            done
        resources:
          requests:
            cpu: "15m"
            memory: 15Mi
status: {}
