apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
  namespace: default
type: Opaque
data:
    # Replace these placeholder hashes with your own Base64 values
  # 'LiveUserPass2026!' encoded: TGl2ZVVzZXJQYXNzMjAyNiE=
  MYSQL_PASSWORD: "TGl2ZVVzZXJQYXNzMjAyNiE=" 
  # 'LiveRootPass2026!' encoded: TGl2ZVJvb3RQYXNzMjAyNiE=
  MYSQL_ROOT_PASSWORD: "TGl2ZVJvb3RQYXNzMjAyNiE=" 
